### ISSUE TITLE
Inconsistency detected by ld.so: dl-lookup.c on Linux

### ISSUE THREAD

**Issue by flamendless** [WinterAlexander/NormalPainter#11]
Running on linux with `java -jar normalpainter.jar` gives me this error:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/home/brbl/Softwares/normalpainter/normalpainter.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Inconsistency detected by ld.so: dl-lookup.c: 105: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
```

System info:
```
OS: Manjaro Linux x86_64 
Host: PC-VJ14ACB7ZEL8 
Kernel: 5.10.7-3-MANJARO 
Uptime: 37 days, 6 hours, 6 mins 
Packages: 1254 (pacman) 
Shell: zsh 5.8 
Resolution: 1280x800 
WM: i3 
Theme: Adapta-Nokto-Eta-Maia [GTK2/3] 
Icons: Papirus-Adapta-Nokto-Maia [GTK2/3] 
Terminal: terminator 
CPU: Intel Core 2 Duo U9400 (2) @ 1.401GHz 
GPU: Intel Mobile 4 Series Chipset 
Memory: 1845MiB / 2951MiB 
```

**Comment by WinterAlexander** [comment]
Hi! This is an issue with LWJGL 2. See the solution here:

https://stackoverflow.com/questions/55847497/how-do-i-troubleshoot-inconsistency-detected-dl-lookup-c-111-java-result-12

The solution is to switch to a different version of Java. You haven't mentionned which one you are using, but I doubt you are using java 8.

We will eventually switch to LWJGL 3 to fix all those issues.

**Comment by flamendless** [comment]
Thanks. I got it running but not actually coz my device only supports opengl 2.1 :(

**Comment by WinterAlexander** [comment]
Ah it's unfortunate! I wish there was a way to make it work with OpenGL 2.1 but the lighting technique I'm using requires OpenGL 3.2 for the multi render target feature.
